apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsnode-deployment
  labels:
    app: jsnode
spec:
  replicas: 3  # Increased replicas for better availability
  selector:
    matchLabels:
      app: jsnode
  template:
    metadata:
      labels:
        app: jsnode
    spec:
      containers:
      - name: jsnode-container
        image: nginx:latest  # You can change this to your custom image
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 5
