apiVersion: v1
kind: Service
metadata:
  name: jsnode-service
  labels:
    app: jsnode
spec:
  type: NodePort
  selector:
    app: jsnode
  ports:
  - protocol: TCP
    port: 80         # Port exposed by the service
    targetPort: 80   # Port the container listens on
    nodePort: 30080  # Optional: explicitly define the node port (30000–32767)
